### ISSUE TITLE
Incompatible with Node.js 10.9.0 Current

### ISSUE THREAD

**Issue by luixxiul** [mozilla/contain-facebook#172]
(Related with building)

### Actual behavior

`npm i` with Node 10.9.0 Current installed results in an error related with `../dtrace_provider.cc:89:35`.

````bash
Brave-MacBook-Pro:contain-google Suguru$ npm i

> dtrace-provider@0.8.6 install /Users/Suguru/contain-google/node_modules/dtrace-provider
> node-gyp rebuild || node suppress-error.js

  LD_LIBRARY_PATH=/Users/Suguru/contain-google/node_modules/dtrace-provider/build/Release/lib.host:/Users/Suguru/contain-google/node_modules/dtrace-provider/build/Release/lib.target:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd ../.; bash build.sh
+ buildUSDT
+ [[ -z '' ]]
+ [[ -z /Users/Suguru/contain-google ]]
+ unset MAKEFLAGS
++ node -e 'console.log(process.arch === '\''x64'\'' ? '\''x86_64'\'' : '\''i386'\'')'
+ export ARCH=x86_64
+ ARCH=x86_64
+ echo 'Building libusdt for x86_64'
Building libusdt for x86_64
+ [[ -z '' ]]
++ which gmake
+ MAKE=
+ [[ -z '' ]]
+ MAKE=make
+ make -C libusdt clean all
rm -f *.gch
rm -f *.o
rm -f libusdt.a
rm -f test_usdt
rm -f test_usdt32
rm -f test_usdt64
rm -f test_mem_usage
gcc -O2 -Wall -arch x86_64   -c -o usdt.o usdt.c
gcc -O2 -Wall -arch x86_64   -c -o usdt_dof_file.o usdt_dof_file.c
gcc -arch x86_64 -o usdt_tracepoints.o -c usdt_tracepoints_x86_64.s
gcc -O2 -Wall -arch x86_64   -c -o usdt_probe.o usdt_probe.c
gcc -O2 -Wall -arch x86_64   -c -o usdt_dof.o usdt_dof.c
gcc -O2 -Wall -arch x86_64   -c -o usdt_dof_sections.o usdt_dof_sections.c
rm -f libusdt.a
ar cru libusdt.a usdt.o usdt_dof_file.o usdt_tracepoints.o usdt_probe.o usdt_dof.o usdt_dof_sections.o 
ranlib libusdt.a
+ LIBUSDT_STATUS=0
+ [[ 0 -ne 0 ]]
+ buildNDTP
+ [[ -z '' ]]
+ [[ -z /Users/Suguru/contain-google ]]
+ node-gyp rebuild -C src
  c++ '-DNODE_GYP_MODULE_NAME=DTraceProviderBindings' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/Users/Suguru/.node-gyp/10.8.0/include/node -I/Users/Suguru/.node-gyp/10.8.0/src -I/Users/Suguru/.node-gyp/10.8.0/deps/openssl/config -I/Users/Suguru/.node-gyp/10.8.0/deps/openssl/openssl/include -I/Users/Suguru/.node-gyp/10.8.0/deps/uv/include -I/Users/Suguru/.node-gyp/10.8.0/deps/zlib -I/Users/Suguru/.node-gyp/10.8.0/deps/v8/include -I../../libusdt -I../../../nan  -Os -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=gnu++1y -stdlib=libc++ -fno-rtti -fno-exceptions -fno-threadsafe-statics -fno-strict-aliasing -MMD -MF ./Release/.deps/Release/obj.target/DTraceProviderBindings/dtrace_provider.o.d.raw   -c -o Release/obj.target/DTraceProviderBindings/dtrace_provider.o ../dtrace_provider.cc
../dtrace_provider.cc:52:23: warning: 'Utf8Value' is deprecated
      [-Wdeprecated-declarations]
    String::Utf8Value name(info[0]->ToString());
                      ^
/Users/Suguru/.node-gyp/10.8.0/include/node/v8.h:2851:5: note: 'Utf8Value' has
      been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/Suguru/.node-gyp/10.8.0/include/node/v8config.h:327:29: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../dtrace_provider.cc:60:25: warning: 'Utf8Value' is deprecated
      [-Wdeprecated-declarations]
      String::Utf8Value mod(info[1]->ToString());
                        ^
/Users/Suguru/.node-gyp/10.8.0/include/node/v8.h:2851:5: note: 'Utf8Value' has
      been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/Suguru/.node-gyp/10.8.0/include/node/v8config.h:327:29: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../dtrace_provider.cc:89:35: error: no matching member function for call to
      'NewInstance'
    v8::Local<Object> pd = klass->NewInstance();
                           ~~~~~~~^~~~~~~~~~~
/Users/Suguru/.node-gyp/10.8.0/include/node/v8.h:3956:44: note: candidate
      function not viable: requires single argument 'context', but no arguments
      were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
/Users/Suguru/.node-gyp/10.8.0/include/node/v8.h:3953:44: note: candidate
      function not viable: requires 3 arguments, but 0 were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
../dtrace_provider.cc:96:10: warning: 'ForceSet' is deprecated
      [-Wdeprecated-declarations]
    Nan::ForceSet(pd, Nan::New<String>("__prov__").ToLocalChecked(), obj,
         ^
../../../nan/nan_maybe_43_inl.h:130:1: note: 'ForceSet' has been explicitly
      marked deprecated here
NAN_DEPRECATED inline Maybe<bool> ForceSet(
^
../../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../dtrace_provider.cc:102:27: warning: 'Utf8Value' is deprecated
      [-Wdeprecated-declarations]
        String::Utf8Value type(info[i + 1]->ToString());
                          ^
/Users/Suguru/.node-gyp/10.8.0/include/node/v8.h:2851:5: note: 'Utf8Value' has
      been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/Suguru/.node-gyp/10.8.0/include/node/v8config.h:327:29: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../dtrace_provider.cc:118:23: warning: 'Utf8Value' is deprecated
      [-Wdeprecated-declarations]
    String::Utf8Value name(info[0]->ToString());
                      ^
/Users/Suguru/.node-gyp/10.8.0/include/node/v8.h:2851:5: note: 'Utf8Value' has
      been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/Suguru/.node-gyp/10.8.0/include/node/v8config.h:327:29: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
5 warnings and 1 error generated.
make[1]: *** [Release/obj.target/DTraceProviderBindings/dtrace_provider.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "-C" "src"
gyp ERR! cwd /Users/Suguru/contain-google/node_modules/dtrace-provider/src
gyp ERR! node -v v10.8.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
+ NODE_GYP_STATUS=1
+ [[ 1 -ne 0 ]]
+ fail 1
+ [[ -z '' ]]
+ [[ -z /Users/Suguru/contain-google ]]
+ [[ '' == \h\a\r\d ]]
+ exit 0
  touch Release/obj.target/ndtp.stamp

> fsevents@1.1.3 install /Users/Suguru/contain-google/node_modules/fsevents
> node install

node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.3 and node@10.8.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.3 and node@10.8.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
gyp ERR! clean error 
gyp ERR! stack Error: EINVAL: invalid argument, rmdir 'build/Release/.deps/Users/eshanker/Code/fsevents/lib/binding'
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "clean"
gyp ERR! cwd /Users/Suguru/contain-google/node_modules/fsevents
gyp ERR! node -v v10.8.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/Suguru/contain-google/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:249:5)
node-pre-gyp ERR! System Darwin 17.7.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/Suguru/contain-google/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/Suguru/contain-google/node_modules/fsevents
node-pre-gyp ERR! node -v v10.8.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean' (1)

> sinon@4.4.9 postinstall /Users/Suguru/contain-google/node_modules/sinon
> node scripts/support-sinon.js

Have some ❤️  for Sinon? You can support the project via Open Collective:
 > https://opencollective.com/sinon/donate


> spawn-sync@1.0.15 postinstall /Users/Suguru/contain-google/node_modules/spawn-sync
> node postinstall

Traceback (most recent call last):: info lifecycle webextensions-jsdom@0.10.0~p
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 538, in main
    return gyp_main(args)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 502, in gyp_main
    'cwd': os.getcwd(),
OSError: [Errno 2] No such file or directory
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/Suguru/contain-google/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/Suguru/contain-google/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64"
gyp ERR! cwd /Users/Suguru/contain-google/node_modules/fsevents
gyp ERR! node -v v10.8.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

added 1347 packages from 1265 contributors and audited 6251 packages in 43.504s
found 42 vulnerabilities (9 low, 28 moderate, 3 high, 2 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
````

### Expected behavior

The error should not be produced on the latest Node.js

### Steps to reproduce
1. Install Node.js 10.9.0 Current
2. Run `npm i`

### Notes

After switching Node to 8.11.4 LTS, `npm i` and `npm run test` pass.

**Comment by nemoload** [comment]
I can confirm this and that's why all the new pull requests will fail as Travis uses Node 10 now.
