### ISSUE TITLE
Build issues: `npm test` fails with assertion error

### ISSUE THREAD

**Issue by doronbehar** [mozilla/contain-facebook#177]
I would like to fork this add-on in order to create a similar container add-on with a different set of domains. I've cloned it on my machine and I tested the `1.3.1` tag and the `master` branch with `npm ci` and then `npm test` and I got the following error:

```
  1) Already Open Reopen
       Add-on initializes with already open but still loading Tab
         should wait for still loading tabs and then reopen them:
     AssertionError: expected stub to have been called with arguments matching { cookieStoreId: "firefox-container-5", url: "https://www.facebook.com" }
      at Context.it (test/features/already-open-reopen.test.js:69:59)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by stoically** [comment]
Just tried with a fresh clone and

```
npm install
npm test
```

is all green. Can you provide some more info like Operating System, NodeJS version installed and `npm ls sinon`?

**Comment by doronbehar** [comment]
```
$ node --version
v10.11.0
$ npm --version
6.4.1
$ npm ls sinon
contain-facebook@1.4.0 /var/code/doron/contain-facebook
├── sinon@4.4.9 
└─┬ webextensions-jsdom@0.10.0
  └─┬ webextensions-api-fake@0.5.0
    └─┬ sinon-chrome@2.3.1
      └── sinon@4.4.9  deduped

```

`npm install` gives me the following messages:
```
> dtrace-provider@0.8.6 install /var/code/doron/contain-facebook/node_modules/dtrace-provider
> node-gyp rebuild || node suppress-error.js

make: Entering directory '/var/code/doron/contain-facebook/node_modules/dtrace-provider/build'
  TOUCH Release/obj.target/DTraceProviderStub.stamp
make: Leaving directory '/var/code/doron/contain-facebook/node_modules/dtrace-provider/build'

> sinon@4.4.9 postinstall /var/code/doron/contain-facebook/node_modules/sinon
> node scripts/support-sinon.js

Have some ❤️  for Sinon? You can support the project via Open Collective:
 > https://opencollective.com/sinon/donate


> spawn-sync@1.0.15 postinstall /var/code/doron/contain-facebook/node_modules/spawn-sync
> node postinstall

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 1347 packages from 1265 contributors and audited 6251 packages in 15.726s
found 42 vulnerabilities (9 low, 28 moderate, 3 high, 2 critical)
```

**Comment by nemoload** [comment]
I have the same issue I think it's related to #172
